//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImgGiaoDien
    {
        public int id_img { get; set; }
        public string url { get; set; }
        public string mo_ta_img { get; set; }
        public string dieu_huong_img { get; set; }
        public string loai_img { get; set; }
    }
}
