//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImgSanPham
    {
        public int id_img { get; set; }
        public string id_san_pham { get; set; }
        public string url { get; set; }
        public string mo_ta_img { get; set; }
        public bool main { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
