//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietHoaDon = new HashSet<ChiTietHoaDon>();
            this.GioHang = new HashSet<GioHang>();
            this.ImgSanPham = new HashSet<ImgSanPham>();
        }
    
        public string id_san_pham { get; set; }
        public Nullable<int> id_danh_muc { get; set; }
        public Nullable<int> id_thuong_hieu { get; set; }
        public string ten_san_pham { get; set; }
        public decimal gia_san_pham { get; set; }
        public Nullable<double> phan_tram_khuyen_mai { get; set; }
        public int so_luong_ton_kho { get; set; }
        public string mo_ta_san_pham { get; set; }
        public string tinh_nang_san_pham { get; set; }
        public string gioi_tinh { get; set; }
        public Nullable<int> so_thang_bao_hanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDon { get; set; }
        public virtual DanhMucSanPham DanhMucSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImgSanPham> ImgSanPham { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
    }
}
